version: '3'

services:
  db1:
    container_name: mssql-server-2019-samplesdb
    build:
      context: .
      dockerfile: Dockerfile
    hostname:
        sql2019
    domainname:
        enriquecatala.com    
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    #volumes:
    #  - d:/:/data
    ports:
      - "14333:1433"
