version: '2.2'

services:
  db1:
    container_name: mssql-server-samplesdb
    build:
      context: .
      dockerfile: Dockerfile
    hostname:
        mssql-samplesdb
    domainname:
        enriquecatala.com    
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      INCLUDE_BIG_DATABASES: "${INCLUDE_BIG_DATABASES}"
      FORCE_ATTACH_IF_MDF_EXISTS: "${FORCE_ATTACH_IF_MDF_EXISTS}"
    # volumes:
    #   - ${LOCAL_MOUNTPOINT}:/var/opt/mssql/data
    # user: "10001:0"
    ports:
      - "14333:1433"
    mem_limit: 8Gb
    cpu_count: 4
