version: '2.2'

services:
  db1:
    container_name: mssql-server-2019-samplesdb-persistent
    build:
      context: .
      dockerfile: Dockerfile-persistentvolume
    hostname:
        sql2019
    domainname:
        enriquecatala.com    
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - ${LOCAL_MOUNTPOINT}:/local_mountpoint
    ports:
      - "14333:1433"
    mem_limit: 8Gb
